// public copy — generated by deploy_site.sh (private fields stripped)
window.COCKPIT_LIVE = {
 "generated": "2026-07-02 09:50",
 "date": "2026-07-02",
 "price": "$60,066",
 "composite": 0.17,
 "verdict": "Bottoming — BTC sits in the composite band that marked the 2015 / 2018 / 2022 lows (n=3), sentiment at extreme fear, macro still a headwind. No price/valuation divergence.",
 "div": {
  "on": false
 },
 "macro": {
  "state": "headwind",
  "netLiq": "$5.82T",
  "netLiqTrend": "falling",
  "dxy": "120.9",
  "real10y": "2.2%",
  "fed": "hold"
 },
 "t": [
  "0.10",
  "up",
  "deep below the long-term mean",
  "stretched to the downside, like past accumulation zones"
 ],
 "v": [
  "MVRV 1.13",
  "up",
  "barely above cost basis",
  "holders near break-even, not euphoric"
 ],
 "s": [
  "RSI 34 · F&G 19",
  "up",
  "crowd in extreme fear, momentum cold",
  "extreme fear with momentum cold — compare the past lows/tops"
 ],
 "dom": [
  "BTC.D 55.7%",
  "up",
  "BTC-led, no alt-season froth",
  "capital hiding in BTC, not chasing alts"
 ],
 "narrative": [
  {
   "dir": "up",
   "text": "Composite 0.16 → 0.17 (still bottoming)."
  },
  {
   "dir": "up",
   "text": "Fear & Greed 11 → 19 (extreme fear)."
  },
  {
   "dir": "down",
   "text": "Net liquidity 5.82T and falling."
  }
 ],
 "invalidation": "(private — kept in the weekly log)"
};
