// public copy — generated by deploy_site.sh (private fields stripped)
window.COCKPIT_LIVE = {
 "generated": "2026-07-03 15:29",
 "date": "2026-07-03",
 "price": "$61,438",
 "composite": 0.18,
 "verdict": "Bottoming — BTC sits in the composite band that marked the 2015 / 2018 / 2022 lows (n=3), sentiment at extreme fear, macro a tailwind. No price/valuation divergence.",
 "div": {
  "on": false
 },
 "macro": {
  "state": "tailwind",
  "netLiq": "$5.84T",
  "netLiqTrend": "rising",
  "dxy": "120.9",
  "real10y": "2.25%",
  "fed": "hold"
 },
 "t": [
  "0.11",
  "up",
  "deep below the long-term mean",
  "stretched to the downside — the zone that preceded prior lows"
 ],
 "v": [
  "MVRV 1.16",
  "up",
  "barely above cost basis",
  "holders near break-even, not euphoric"
 ],
 "s": [
  "RSI 36 · F&G 21",
  "up",
  "crowd in extreme fear, momentum cold",
  "extreme fear with momentum cold — compare the past lows/tops"
 ],
 "dom": [
  "BTC.D 55.6%",
  "up",
  "BTC-led, no alt-season froth",
  "capital hiding in BTC, not chasing alts"
 ],
 "narrative": [
  {
   "dir": "up",
   "text": "Composite 0.16 → 0.18 (still bottoming)."
  },
  {
   "dir": "up",
   "text": "Fear & Greed 11 → 21 (extreme fear)."
  },
  {
   "dir": "up",
   "text": "Net liquidity 5.84T and rising."
  }
 ],
 "invalidation": "(private — kept in the weekly log)",
 "ref": [
  {
   "name": "NUPL",
   "reading": "0.14",
   "state": "hope",
   "ll": "lags",
   "note": "pure transform of MVRV — display only, never composite"
  },
  {
   "name": "Puell",
   "reading": "0.62",
   "state": "mid, near bottom band",
   "ll": "coincident",
   "note": "bottoms-only instrument — top band dead post-halvings"
  },
  {
   "name": "Hash Ribbon",
   "reading": "0.97",
   "state": "miner capitulation",
   "ll": "confirms lows",
   "note": "event flag — false signals May/Jul 2025"
  },
  {
   "name": "SSR osc",
   "reading": "-0.91",
   "state": "loosening",
   "ll": "leads",
   "note": "oscillator form — stables ≠ all BTC-bound"
  },
  {
   "name": "BMSB",
   "reading": "below -14%",
   "state": "bear regime",
   "ll": "coincident",
   "note": "trend-regime gate — 20W SMA + 21W EMA"
  }
 ],
 "rel": {
  "pct": 0.05,
  "band": "bottom band"
 },
 "posts": {
  "thread": [
   "The Cockpit — weekly read · 2026-07-03\n\nBTC $61,438. Composite zone: BOTTOMING.\n\nA cycle state-read from the instrument panel — where we are, never what to do about it. 🧵",
   "Bottoming — BTC sits in the composite band that marked the 2015 / 2018 / 2022 lows (n=3), sentiment at extreme fear, macro a tailwind. No price/valuation divergence.\n\nRead: base rate + macro mechanism, medium conviction. (ETF-era caveat applies to every claim in this thread.)",
   "Under the hood:\n· Trend — deep below the long-term mean\n· Valuation — barely above cost basis\n· Sentiment — crowd in extreme fear, momentum cold\n(each read against all 7 cycle pivots, n=7)",
   "Cross-checks (n=7):\n· NUPL 0.14 — hope (MVRV transform)\n· Puell 0.62 — mid, near bottom band (bottoms-only)\n· Hash Ribbon 0.97 — miner capitulation (false-fires known)\n· SSR osc -0.91 — loosening (stables ≠ all BTC-bound)\n· BMSB below -14% — bear regime (regime gate)",
   "Do the cross-checks confirm? Not fully:\n\n· NUPL 0.14 reads 'hope' — the 3 pinned lows sat in capitulation (<0)\n· Puell 0.62 sits above the <0.5 band that held at all 3 lows\n\nNear the historical low profile, not at it (n=3).\nReflexivity: famous signals get front-run.",
   "Macro backdrop: TAILWIND.\nNet liquidity $5.84T (rising) · real 10y 2.25% · Fed hold.\n\nMechanism claim, not a base rate: liquidity drives the risk-asset bid.",
   "History:\n\nMeasured from the n=3 hindsight-pinned pivots ('15, '18, '22 lows), the following 12 months ran very roughly +120% to +160%. Nobody catches exact pivots live — real reads arrive earlier and eat more downside. ETF era differs from all 3. Base rate, medium conviction.",
   "Two rulers, one market:\n· vs all of history: BOTTOMING\n· vs its own 4-year window: BOTTOM BAND (5th percentile of the window)\n\nBoth lenses agree this week.",
   "Regime caveat: the ETF era differs structurally from every prior cycle, and n is tiny everywhere in bitcoin. This is a state-read, not a forecast. Context and education — never financial advice."
  ],
  "signals": [
   {
    "name": "Composite",
    "text": "Composite check · 2026-07-03\n\nBTC $61,438 — zone: BOTTOMING (3-dial composite vs 7 pivots, n=7).\n\nMeasured from the n=3 hindsight-pinned pivots ('15, '18, '22 lows), the following 12 months ran very roughly +120% to +160%. Best case, not expected.\n\nState-read, not advice."
   },
   {
    "name": "Trend",
    "text": "Trend check · 2026-07-03\n\nLog-reg channel 0.11 — deep below the long-term mean (n=7 pivots for context).\n\nstory: stretched to the downside — the zone that preceded prior lows.\n\nState-read, not advice."
   },
   {
    "name": "Valuation",
    "text": "Valuation check · 2026-07-03\n\nMVRV 1.16 — barely above cost basis (n=7 pivots).\n\nstory: holders near break-even, not euphoric.\n\nState-read, not advice."
   },
   {
    "name": "Sentiment",
    "text": "Sentiment check · 2026-07-03\n\nRSI 36 · F&G 21 — crowd in extreme fear, momentum cold (n=7 pivots).\n\nstory: extreme fear with momentum cold — compare the past lows/tops.\n\nState-read, not advice."
   },
   {
    "name": "Dominance",
    "text": "Dominance check · 2026-07-03\n\nBTC.D 55.6% — BTC-led, no alt-season froth.\n\nstory: capital hiding in BTC, not chasing alts.\n\nShort history — mechanism read, no real base rate.\n\nState-read, not advice."
   },
   {
    "name": "NUPL",
    "text": "NUPL check · 2026-07-03\n\n0.14 — hope.\n\nIt's a pure transform of MVRV — a display lens, n=7 backfill.\n\nState-read, not advice."
   },
   {
    "name": "Puell",
    "text": "Puell check · 2026-07-03\n\n0.62 — mid, near bottom band.\n\nBottoms-only instrument: its <0.5 band held at all n=3 pinned lows; its top band died with the halvings.\n\nState-read, not advice."
   },
   {
    "name": "Hash Ribbon",
    "text": "Hash Ribbon check · 2026-07-03\n\n0.97 — miner capitulation.\n\nEvent flag with false-fires on record (May/Jul '25). Famous enough to be front-run.\n\nState-read, not advice."
   },
   {
    "name": "SSR osc",
    "text": "SSR osc check · 2026-07-03\n\n-0.91 — loosening.\n\nOscillator vs 200d trend. Stablecoins aren't all BTC-bound — mechanism read only.\n\nState-read, not advice."
   },
   {
    "name": "BMSB",
    "text": "BMSB check · 2026-07-03\n\nbelow -14% — bear regime.\n\n20W SMA + 21W EMA regime gate. Famous — reflexivity discount applies. n=7 backfill.\n\nState-read, not advice."
   }
  ],
  "combos": [
   {
    "name": "Near, not at",
    "text": "Disagreement · 2026-07-03\n\nComposite: bottoming band. But:\n· NUPL 0.14 reads 'hope' — the 3 pinned lows sat in capitulation (<0)\n· Puell 0.62 sits above the <0.5 band that held at all 3 lows\n\nNear the n=3 pinned-low profile, not at it. The gap is the read.\n\nState-read, not advice."
   }
  ]
 }
};
